spring:
  application:
    name: coffee_order_be

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: org.prgrms.coffee_order_be.product.entity; org.prgrms.coffee_order_be.order.entity
  type-handlers-package: org.prgrms.coffee_order_be.common.util
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    org.hibernate.SQL: trace
    org.hibernate.type.descriptor: trace
    root: info